default_settings: null

behaviors:
  Basic:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32            # More stable updates for simple envs
      buffer_size: 512          # Small buffer since the env is simple
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95               # Slightly lower for faster reward response
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64          # Smaller net is fine for this basic task
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 100000           # Faster iterations for testing
    time_horizon: 32            # Faster agent response
    summary_freq: 1000          # Way more frequent logs for progress tracking
